version: "3"

services:
  site:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: "maksimlebedev_redirect"
    restart: always
    environment:
      - VIRTUAL_HOST=$VIRTUAL_HOST
      - REDIRECT_HOST=$REDIRECT_HOST
      - LETSENCRYPT_HOST=$LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL=$LETSENCRYPT_EMAIL

networks:
  default:
    name: nginx-proxy
